In [1]:
# Importing numpy
import numpy as np

In [78]:
# Create an array
arr = np.array([[10, 12, 33], [45, 65, 76]])
arr.shape


(2, 3)

# Reshape the array

In [68]:
print("Original array: \n",arr)
arr_reshaped = np.reshape(arr, (3, 2))
print("Reshaped array:\n", arr_reshaped)

Original array: 
 [[10 12 33]
 [45 65 76]]
Reshaped array:
 [[10 12]
 [33 45]
 [65 76]]


# Transpose the array

In [69]:
print("Original array: \n",arr)
arr_transposed = np.transpose(arr)
print("Transposed array:\n", arr_transposed)

Original array: 
 [[10 12 33]
 [45 65 76]]
Transposed array:
 [[10 45]
 [12 65]
 [33 76]]


# Flatten the array

In [70]:
print("Original array: \n",arr)
arr_flattened = arr.flatten()
print("Flattened array:\n", arr_flattened)

Original array: 
 [[10 12 33]
 [45 65 76]]
Flattened array:
 [10 12 33 45 65 76]


# Concatenate two arrays

In [71]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Original array 1: \n",arr1)
print("Original array 2: \n",arr2)
arr_concatenated = np.concatenate((arr1, arr2))
print("Concatenated array:\n", arr_concatenated)

Original array 1: 
 [1 2 3]
Original array 2: 
 [4 5 6]
Concatenated array:
 [1 2 3 4 5 6]


# Concatenate two  2D arrays

In [72]:
arr1 = np.array([[1, 2, 3],[11,12,13]])
arr2 = np.array([[4, 5, 6],[14,15,16]])
print("Original array 1: \n",arr1)
print("Original array 2: \n",arr2)
arr_concatenated = np.concatenate((arr1, arr2))
print("Concatenated array:\n", arr_concatenated)
#arr_concatenated.shape


Original array 1: 
 [[ 1  2  3]
 [11 12 13]]
Original array 2: 
 [[ 4  5  6]
 [14 15 16]]
Concatenated array:
 [[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [14 15 16]]


# Split an array

In [73]:
arr_splitted = np.array_split(arr, 2)
print("Splitted array:\n", arr_splitted)

Splitted array:
 [array([[10, 12, 33]]), array([[45, 65, 76]])]


# Inserting value in an array

In [74]:
print("Original array :\n", arr)
arr_inserted_col = np.insert(arr, 2, 5, axis=1)
print("Inserted array:\n", arr_inserted_col)

arr_inserted_row = np.insert(arr, 1, 5, axis=0)
print("Inserted array:\n", arr_inserted_row)

Original array :
 [[10 12 33]
 [45 65 76]]
Inserted array:
 [[10 12  5 33]
 [45 65  5 76]]
Inserted array:
 [[10 12 33]
 [ 5  5  5]
 [45 65 76]]


# adding values in 2D array with append

In [79]:
#adding elements as row
print("Original array :\n", arr)
r=np.array([7,2,3])
arr_append_row = np.append(arr, [r], axis=0)
print("Array after append: \n", arr_append)

Original array :
 [[10 12 33]
 [45 65 76]]
Array after append: 
 [[10 12 33]
 [45 65 76]
 [ 7  2  3]]
Original array :
 [[10 12 33]
 [45 65 76]]
Array after append: 
 [[ 10  12  33 100]
 [ 45  65  76 200]]


In [ ]:
#adding elements as col
print("Original array :\n", arr)
c=np.array([100,200])
cc=np.reshape(c,(-1,1))
arr_append_col = np.append(arr, cc, axis=1)
print("Array after append: \n", arr_append_col)

# Sorting an array

In [88]:
# Creating a 2D array
arr = np.array([[3, 2, 7],
                [6, 8, 4],
                [9, 5, 1]])
print("Original Arrya:\n", arr)
# Sorting along the rows
arr.sort(axis=1)
print("Sorted 2D Array:\n", arr)
arr = np.array([[3, 2, 7],
                [6, 8, 4],
                [9, 5, 1]])
# Sorting along the coluns
arr.sort(axis=0)
print("Sorted 2D Array at column:\n", arr)

Original Arrya:
 [[3 2 7]
 [6 8 4]
 [9 5 1]]
Sorted 2D Array:
 [[2 3 7]
 [4 6 8]
 [1 5 9]]
Sorted 2D Array at column:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
