# Dot product: np.dot()

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)

32


# Matrix multiplication: np.matmul()

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.matmul(A, B)
print(product) 

[[19 22]
 [43 50]]


# Matrix inversion: np.linalg.inv()

In [3]:
A = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(A)
print(inverse)  

[[-2.   1. ]
 [ 1.5 -0.5]]


# Determinant: np.linalg.det()

In [4]:
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
print(det)  

-2.0000000000000004


# Eigenvalues and eigenvectors: np.linalg.eig()

In [5]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("eigenvalues:\n",eigenvalues)     
print("eigenvectors:\n", eigenvectors)    


eigenvalues:
 [-0.37228132  5.37228132]
eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Matrix power: np.linalg.matrix_power()

In [6]:
A = np.array([[1, 2], [3, 4]])
power = np.linalg.matrix_power(A, 3)
print(power)  

[[ 37  54]
 [ 81 118]]


# Singular value decomposition: np.linalg.svd()

In [7]:
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, V = np.linalg.svd(A)
print(U)  
print(S)  
print(V)  

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


for more on this [click)[https://numpy.org/doc/stable/reference/routines.linalg.html}