In [2]:
#importing library
import numpy as np

# Creating two arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([26, 27, 28, 29, 30])
print("Array 1:", arr1)
print("Array 2:", arr2)

# Element-wise addition of two arrays

In [4]:
#using +
print(arr1+arr2)

#using np.add()
add=np.add(arr1, arr2)
print("Addition of Arrays:", add)

[36 47 58 69 80]
Addition of Arrays: [36 47 58 69 80]


# Element-wise subtraction of two arrays

In [5]:
#using -
#subtracting arr2 from arr1
print(arr1-arr2)

#using np.subtract()
sub=np.subtract(arr1, arr2)
print("Subtraction of Arrays:", sub)

[-16  -7   2  11  20]
Subtraction of Arrays: [-16  -7   2  11  20]


# Element-wise multiplication of two arrays

In [7]:
#using *
print(arr1 * arr2)

#using np.multiply()
mul=np.multiply(arr1, arr2)
print("Multiplication of Arrays:", mul)

[ 260  540  840 1160 1500]
Multiplication of Arrays: [ 260  540  840 1160 1500]


# Element-wise division of two arrays

In [8]:
#using /
print(arr1 / arr2)

#using np.divide()
div=np.divide(arr1, arr2)
print("Division of Arrays:", div)


[0.38461538 0.74074074 1.07142857 1.37931034 1.66666667]
Division of Arrays: [0.38461538 0.74074074 1.07142857 1.37931034 1.66666667]


# Finding the dot product of two arrays

In [17]:
dot_prod = np.dot(arr1, arr2)
print("Dot Product of Arrays:", dot_prod)

Dot Product of Arrays: 4300


# sum of elemets of a 1D array

In [18]:
print(arr1)
print(np.sum(arr1))

[10 20 30 40 50]
150


# sum of all elemets of a 2D array

In [ ]:
arr_2d= np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

#sum of all elements of 2D array
print(np.sum(arr_2d))

# Row-wise sum of all elements of 2D array

In [19]:
print(np.sum(arr_2d, axis=1))

[10 26]


# Product of all elements of an array

In [11]:
print(arr1)
print(np.prod(arr1))

12000000

# Row-wise product of all elements of 2D array

In [21]:
print(arr_2d)
print(np.prod(arr_2d, axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[  24 1680]


# Additional mathematical functions on the array

In [ ]:
# Creating an array
arr = np.array([11, 25, 36, 74, 95])
print("Array:", arr)

In [ ]:
print("Square Root of Array:", np.sqrt(arr))

In [ ]:
print("Exponential of Array:", np.exp(arr))

In [ ]:
print("Logarithm of Array:", np.log(arr))
print("Logarithm Base 10 of Array:", np.log10(arr))

In [ ]:
print("Absolute Value of Array:", np.abs(arr))

In [ ]:
print("Trigonometric Sine of Array:", np.sin(arr))
print("Trigonometric Cosine of Array:", np.cos(arr))
print("Trigonometric Tangent of Array:", np.tan(arr))

In [ ]:
print("Inverse Trigonometric Sine of Array:", np.arcsin(arr))
print("Inverse Trigonometric Cosine of Array:", np.arccos(arr))
print("Inverse Trigonometric Tangent of Array:", np.arctan(arr))