In [2]:
#importing library
import numpy as np

# Creating two arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([26, 27, 28, 29, 30])
print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [10 20 30 40 50]
Array 2: [26 27 28 29 30]


# Element-wise addition of two arrays

In [3]:
#using +
print(arr1+arr2)

#using np.add()
add=np.add(arr1, arr2)
print("Addition of Arrays:", add)

[36 47 58 69 80]
Addition of Arrays: [36 47 58 69 80]


# Element-wise subtraction of two arrays

In [4]:
#using -
#subtracting arr2 from arr1
print(arr1-arr2)

#using np.subtract()
sub=np.subtract(arr1, arr2)
print("Subtraction of Arrays:", sub)

[-16  -7   2  11  20]
Subtraction of Arrays: [-16  -7   2  11  20]


# Element-wise multiplication of two arrays

In [5]:
#using *
print(arr1 * arr2)

#using np.multiply()
mul=np.multiply(arr1, arr2)
print("Multiplication of Arrays:", mul)

[ 260  540  840 1160 1500]
Multiplication of Arrays: [ 260  540  840 1160 1500]


# Element-wise division of two arrays

In [6]:
#using /
print(arr1 / arr2)

#using np.divide()
div=np.divide(arr1, arr2)
print("Division of Arrays:", div)


[0.38461538 0.74074074 1.07142857 1.37931034 1.66666667]
Division of Arrays: [0.38461538 0.74074074 1.07142857 1.37931034 1.66666667]


# Finding the dot product of two arrays

In [7]:
dot_prod = np.dot(arr1, arr2)
print("Dot Product of Arrays:", dot_prod)

Dot Product of Arrays: 4300


# sum of elemets of a 1D array

In [8]:
print(arr1)
print(np.sum(arr1))

[10 20 30 40 50]
150


# sum of all elemets of a 2D array

In [9]:
arr_2d= np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

#sum of all elements of 2D array
print(np.sum(arr_2d))

[[1 2 3 4]
 [5 6 7 8]]
36


# Row-wise sum of all elements of 2D array

In [10]:
print(np.sum(arr_2d, axis=1))

[10 26]


# Product of all elements of an array

In [11]:
print(arr1)
print(np.prod(arr1))

[10 20 30 40 50]
12000000


# Row-wise product of all elements of 2D array

In [12]:
print(arr_2d)
print(np.prod(arr_2d, axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[  24 1680]


# Additional mathematical functions on the array

In [13]:
# Creating an array
arr = np.array([11, 25, 36, 74, 95])
print("Array:", arr)

Array: [11 25 36 74 95]


In [14]:
print("Square Root of Array:", np.sqrt(arr))

Square Root of Array: [3.31662479 5.         6.         8.60232527 9.74679434]


In [15]:
print("Exponential of Array:", np.exp(arr))

Exponential of Array: [5.98741417e+04 7.20048993e+10 4.31123155e+15 1.37338298e+32
 1.81123908e+41]


In [16]:
print("Logarithm of Array:", np.log(arr))
print("Logarithm Base 10 of Array:", np.log10(arr))

Logarithm of Array: [2.39789527 3.21887582 3.58351894 4.30406509 4.55387689]
Logarithm Base 10 of Array: [1.04139269 1.39794001 1.5563025  1.86923172 1.97772361]


In [17]:
print("Absolute Value of Array:", np.abs(arr))

Absolute Value of Array: [11 25 36 74 95]


In [18]:
print("Trigonometric Sine of Array:", np.sin(arr))
print("Trigonometric Cosine of Array:", np.cos(arr))
print("Trigonometric Tangent of Array:", np.tan(arr))

Trigonometric Sine of Array: [-0.99999021 -0.13235175 -0.99177885 -0.98514626  0.68326171]
Trigonometric Cosine of Array: [ 0.0044257   0.99120281 -0.12796369  0.17171734  0.73017356]
Trigonometric Tangent of Array: [-2.25950846e+02 -1.33526407e-01  7.75047091e+00 -5.73702254e+00
  9.35752472e-01]


In [19]:
print("Inverse Trigonometric Sine of Array:", np.arcsin(arr))
print("Inverse Trigonometric Cosine of Array:", np.arccos(arr))
print("Inverse Trigonometric Tangent of Array:", np.arctan(arr))

Inverse Trigonometric Sine of Array: [nan nan nan nan nan]
Inverse Trigonometric Cosine of Array: [nan nan nan nan nan]
Inverse Trigonometric Tangent of Array: [1.48013644 1.53081764 1.54302569 1.55728364 1.5602704 ]


C:\Users\Pooja\AppData\Local\Temp\ipykernel_22648\3585001951.py:1: RuntimeWarning: invalid value encountered in arcsin
  print("Inverse Trigonometric Sine of Array:", np.arcsin(arr))
C:\Users\Pooja\AppData\Local\Temp\ipykernel_22648\3585001951.py:2: RuntimeWarning: invalid value encountered in arccos
  print("Inverse Trigonometric Cosine of Array:", np.arccos(arr))


# Commulaitve sum

In [28]:
#1D array
print(arr1)
print(np.cumsum(arr1))

#2D array
print(arr_2d)
print(np.cumsum(arr_2d))

#2D array row-wise
print(np.cumsum(arr_2d, axis=1))

[10 20 30 40 50]
[ 10  30  60 100 150]
[[1 2 3 4]
 [5 6 7 8]]
[ 1  3  6 10 15 21 28 36]
[[ 1  3  6 10]
 [ 5 11 18 26]]


# Commulative Product 

In [27]:
#1D Array
print(arr1)
print(np.cumprod(arr1))

#2D array
print(arr_2d)
print(np.cumprod(arr_2d))

#2d array, row-wise
print(np.cumprod(arr_2d, axis=1))
arr_2d.shape

[10 20 30 40 50]
[      10      200     6000   240000 12000000]
[[1 2 3 4]
 [5 6 7 8]]
[    1     2     6    24   120   720  5040 40320]
[[   1    2    6   24]
 [   5   30  210 1680]]


(2, 4)