# Mean of an array

In [9]:
import numpy as np
#1D array
a_1D = np.array([10, 12, 23, 26,34, 55])
print(np.mean(a_1D)) 

26.666666666666668


In [10]:
#2D array
a_2D = np.array([[10, 12, 23],[26, 34, 55]])
print(np.mean(a_2D)) 

26.666666666666668


same as 1D array? because np.mean calculates mean accross the elements.
to find the mean across row we can use axis parameter, as below:-

In [11]:
#2D array mean across rows
print(np.mean(a_2D, axis=1)) 

[15.         38.33333333]


# Median of an array

In [24]:
#1D array
print(a_1D)
print(np.median(a_1D))  

[10 12 23 26 34 55]
24.5


In [25]:
#2D array
print(a_2D)
print(np.median(a_2D))  

[[10 12 23]
 [26 34 55]]
24.5


In [26]:
#2D array median across rows
print(a_2D)
print(np.median(a_2D, axis=1))  

[[10 12 23]
 [26 34 55]]
[12. 34.]


# Standard Deviation of an array

In [27]:
#1D array
print(a_1D)
print(np.std(a_1D))

[10 12 23 26 34 55]
15.073892072793353


In [28]:
#2D array 
print(a_2D)
print(np.std(a_2D))

[[10 12 23]
 [26 34 55]]
15.073892072793353


In [29]:
#2D array std across rows
print(a_2D)
print(np.std(a_2D, axis=1))

[[10 12 23]
 [26 34 55]]
[ 5.71547607 12.22929089]


# Variance of an array

In [30]:
#1D array
print(a_1D)
print(np.var(a_1D))

[10 12 23 26 34 55]
227.22222222222226


In [31]:
#2D array 
print(a_2D)
print(np.var(a_2D))

[[10 12 23]
 [26 34 55]]
227.22222222222226


In [32]:
#2D array variance across rows
print(a_2D)
print(np.var(a_2D, axis=1))

[[10 12 23]
 [26 34 55]]
[ 32.66666667 149.55555556]


# Finding Maximum and Minimum Value

In [33]:
#1D array
print(a_1D)
print("Minimum value:\n",np.min(a_1D))
print("Miximum value:\n",np.max(a_1D))

[10 12 23 26 34 55]
Minimum value:
 10
Miximum value:
 55


In [34]:
#2D array
print(a_2D)
print("Minimum value:\n",np.min(a_2D))
print("Miximum value:\n",np.max(a_2D))

[[10 12 23]
 [26 34 55]]
Minimum value:
 10
Miximum value:
 55


In [35]:
#2D array - row wise max and min values
print(a_2D)
print("Minimum value:\n",np.min(a_2D, axis=1))
print("Miximum value:\n",np.max(a_2D, axis=1))

[[10 12 23]
 [26 34 55]]
Minimum value:
 [10 26]
Miximum value:
 [23 55]


# Correlation Coefficient

In [38]:
a = np.array([[1, 1.5, 3], [4, 5, 6]])
b = np.array([[2, 4, 6], [0, 10, 5]])
print(np.corrcoef(a, b)) 

[[1.         0.96076892 0.96076892 0.24019223]
 [0.96076892 1.         1.         0.5       ]
 [0.96076892 1.         1.         0.5       ]
 [0.24019223 0.5        0.5        1.        ]]


# Histogram

In [39]:
a = np.array([1, 2, 3, 3, 4, 5])
hist, bin_edges = np.histogram(a, bins=2)
print(hist)  
print(bin_edges)  

[2 4]
[1. 3. 5.]
